### ISSUE TITLE
Artifacting when drawing, selecting, dragging, erasing, etc.

### ISSUE THREAD

**Issue by HenriHawk42** [flxzt/rnote#1263]
**Describe the bug**  
Any form of movement on the canvas results in artifacting, generally wallpaper artifacts, but sometimes artifacts from the eraser or selection tool. The main brush will also often default to selection, but it's not consistent. I feel like this is related to the other issue, because if my memory serves me correctly, I didn't have these issues a couple of months ago. I feel like either a system update or a rnote update created this issue.

**To Reproduce**  
I'm not sure how to reproduce this behavior. My apologies.

**Expected behavior**  

**Console Output**  
(I don't know how to get this, I didn't install rnote with flatpak, sorry)

**Screenshots**  
Here's a screen recording of the artifacting. Note that it also occurs with the red border of the eraser tool.

https://github.com/user-attachments/assets/a246d338-a301-44fe-9c75-8759f9fba9d6

**Desktop:**  
 - OS: Arch Linux v6.11.4 (using linux-surface)
 - App Version: Rnote v0.11.0
 - Installation Source: Arch Linux Official repo, I also tried building from source, but the problem wasn't fixed
 - Desktop Environment: Hyprland v0.44.0
 - Display Server: Wayland
 - Input Source: On-Screen-Tablet (Microsoft Surface Laptop Studio)

**Additional context**  
This issue seems very similar to #309

**Comment by rightleftspin** [comment]
I'm getting this same issue after updating an hour ago. My specs are as follows.

OS: Nixos Unstable
App Version: Rnote v0.11.0
Installation Source: Nixpkgs, recently updated
Desktop Environment: Niri 0.1.9
Display Server: Wayland
Input Source: Wacom Tablet

**Comment by ibesmrad** [comment]
I have this issue too in both Hyprland and KDE(with Wayland) and using the latest version of rnote.

**Comment by sodiboo** [comment]
I'm also experiencing this issue on `0.11.0` on NixOS with niri.

The problem is with damage tracking, and only happens with a fractional scale. Somewhere, the damage region is likely rounded to surface-local coordinates (which are integers; one fundamental flaw of the core Wayland protocol that unfortunately cannot be fixed), which is **wrong** and causes off-by-one errors like this. I couldn't easily find the offending code from a quick search for `damage` in this repo, which yields zero code results.

The correct way to implement this is to *ignore* the surface-local coordinates. Because damage is inherently unrelated to surface geometry, there exists a [`damage_buffer`](https://wayland.app/protocols/wayland#wl_surface:request:damage_buffer) requests on `wl_surface`s, which should be used instead. Then, the damage never needs to be rounded and doesn't cause this issue.

The issue doesn't occur on integer scales because then the rounding is exact.

It seems to be the case that every buffer from rnote is an empty buffer with transparent pixels. This issue would be less noticeable if the remainder of the buffer was also content, because then the only effect is that the GPU does slightly more work than necessary. Because the region that wasn't drawn is transparent, it causes the parts that were not drawn to update to a transparent pixel instead. It is part of the windows opaque region, so most compositors will show the incorrectly damaged parts as black, unless you have a window rule making the whole window transparent, in which case it will show your wallpaper or whatever's behind.

Panning removes the artifacts because it redraws the entire buffer and damages the entire buffer.

**Comment by dangooddd** [comment]
I have this issue too, with any level of fractional scaling. Without fractional scaling issue dissappears. Runnig on KDE Plasma 6.2

**Comment by HenriHawk42** [comment]
Ah, that explains it. kinda sucks, because fractional scaling is the only thing that works properly on my laptop due to it being a high dpi screen. normal scale value and everything is too small.

**Comment by HenriHawk42** [comment]
@devraza the scaling appears too large for my laptop (i.e. the buttons are too big)

**Comment by Kneemund** [comment]
I've tried to reproduce this, and I'm getting these artifacts everywhere when fractional scaling is enabled (e.g. when hovering over elements of the workspace browser), not just within the canvas.

Rnote doesn't interact with Wayland directly, but sodiboo might still be on the right track. It could also be a GTK or mutter bug; fractional scaling is experimental after all. I'm not sure, I'll try to do some more testing soon.

**Comment by sodiboo** [comment]
> Rnote doesn't interact with Wayland directly

Yeah, i wasn't able to find much Wayland-specific code. But i am approaching the issue from the perspective of a Wayland compositor (as that's the thing i'm to some extent working on), so i described what is definitely happening at that level.

The actual location of the bug is at some higher level of abstraction, but fundamentally it does look like it's incorrectly rounding the buffer damages to fractional scales (which again, is wrong and unnecessary, because even at the lower level of the stack you are supposed to pass the raw buffer damage, so it shouldn't be rounded *anywhere* along the chain of custody)

**Comment by HenriHawk42** [comment]
switching to an integer scale factor fixed this issue perfectly for me, and this is honestly better because the buttons are bigger for ease of touch. only downside is that other apps are scaled incorrectly. i wonder if i can somehow tell hyprland to use 1.6 scaling for other apps but to use a scale factor of 2 for just rnote

**Comment by HenriHawk42** [comment]
yuhp, i was thinking that myself

**Comment by Doublonmousse** [comment]
I thought `GDK_SCALE=2` would work as a workaround but that isn't activated with the wayland gtk backend (but works on X). Maybe `GDK_BACKEND=x11 GDK_SCALE = 2 rnote` is a passable workaround.

Also, what versions of gtk are you on ? I can't seem to reproduce this on `4.16.5-2.fc41` with fractional scaling on kde (no matter the renderer, though I know there's a fedora specific patch here, probably unrelated though)

**Comment by devraza** [comment]
Just `GDK_BACKEND=x11` was enough to fix the artifacting for me, though the UI still appears blurry/pixelated.
![image](https://github.com/user-attachments/assets/34813526-4181-4ed0-bc7b-b06605af2363)

**Comment by chron-isch** [comment]
I'm having the same issues on a Thinkpad X1 Tablet Gen 2.

Arch 6.13
Desktop: Sway/Wayland
Rnote version: 0.11

The issue first appeared on commit 7e1b3861120199ca02795810ebe63185f50131b1.

PS: Bisecting Rust applications on weak hardware is no fun at all...

**Comment by Doublonmousse** [comment]
@chronically-late If it's this commit, could I know what version of gtk you're building with? From the package manager, the meson setup output or using `GDK_DEBUG=interactive rnote`

If you build with a commit before this one, running
```
GSK_RENDERER=gl rnote
```
will have the issue and
```
GSK_RENDERER=vulkan rnote
```
or
```
GSK_RENDERER=ngl rnote
```
will not (and if the last command doesn't work you're probably on gtk 4.17.x). The issue is a gtk4 one and this may have been fixed on some of the renderers on more recent versions. The bisected commit is us forcing one of the renderer because it was unstable when first introduced as the new default

**Comment by chronically-late** [comment]
@Doublonmousse My gtk version is 4.16.12 and you are correct.
Setting `GSK_RENDERER=gl rnote` for a build from a commit before https://github.com/flxzt/rnote/commit/7e1b3861120199ca02795810ebe63185f50131b1 will introduce the issue while `vulkan` and `ngl` work fine.

**Comment by Doublonmousse** [comment]
@chronically-late Thank you for testing !
I think changing if/how we force the renderer will have to wait for the 4.18.x release to roll out (so that we can force the gtk4 version to be  >=4.18 and change settings without breaking things on older versions)

**Comment by SeeStarz** [comment]
Hi, I'm using arch linux with hyprland and is having a similar issue when using fractional scaling (a lot of artifacts when drawing and some just appears randomly). Weirdly, the flatpak version does not seem to observe such behaviour? Also, this issue does not seem to happen when rnote is on fullscreen and reappears when it exits fullscreen.

**Comment by cleanerspam** [comment]
So is their no workaround for these artifacts , maybe rnote should switch to QT , it is always GTK that causes weird bugs everywhere in each updates.  I do not face this issue in Xournal++ but it has all the pen and color hidden inside menu requiring several steps whereas rnote has everything mostly needed one click away but these glitches makes it unusable

**Comment by chronically-late** [comment]
@cleanerspam You could either use the Flatpak version @SeeStarz mentioned or you could disable scaling for the output you're using rnote on.
Sadly, both the `vulkan` renderer as well as gtk 4.17 are too unstable to use them (rnote will crash after a few pen strokes).

Also, the comparison to Xournal++ is unfair, it's written in C++ using gtk3/gtkmm, which is decades old, while gtk4/gtk-rs is fairly new and the rust-qt binding would probably cause similar issues.

**Comment by Doublonmousse** [comment]
@chronically-late  Can you retest this on gtk 4.18.2 ? As 4.18 is the next stable this will affect us (if we should bump the gtk dependency now or not, and other people will be affected as well on the stable versions once new distros are updated to gtk 4.18).

The `gl` renderer isn't part of 4.18 anymore (there is only `ngl` and `vulkan` now with the latter as the default on linux)

If it still happen, it'd be good to open an issue upstream on the gtk gitlab page (with backtraces if possible : if `RUST_BACKTRACE=1` doesn't return anything, then `gdb rnote`  followed by typing `bt` after the crash and posting the output).
We should at the very least report gtk issue upstream so that they can (hopefully) be fixed.

As for the UI framework, for gtk4 the bindings rarely were an issue.
Qt isn't very used with rust (there's a few projects but maybe not mature yet or maintained?)

There isn't really good alternatives outside of these two for now for our use (we absolutely need good pen and touch support and a good enough reason to switch if we do so for what we'd want to do with the interface, rendering, cross-platform support, general stability etc... And time to do so as well)

**Comment by chronically-late** [comment]
@Doublonmousse Tested with glib-2.0 2.84.0, gio-2.0 2.84.0, cairo 1.18.4, gtk4 4.18.2 and poppler 25.03.0.
Artifacts are still gone, but rnote crashes after 2-3 strokes with `ngl` or `vulkan`.

**Comment by Doublonmousse** [comment]
@chronically-late Do you have any terminal log from using `RUST_BACKTRACE=1` (and if not, can you run `gdb rnote` then typing `run`, reproducing the crash, typing `bt` in the terminal and pasting the output) ?

This would facilitate a lot debugging (and make it possible to open an issue on the gtk side)

**Comment by chronically-late** [comment]
@Doublonmousse Sure, no problem, but it might take a day.

**Comment by chronically-late** [comment]
@Doublonmousse Sure, no problem. 

Compiled with `arch-meson rnote build -Dcli=true -Dprofile=devel`

```
% gdb ./rnote                                                                                                             [19:15:22]
GNU gdb (GDB) 16.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./rnote...
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/chron/builds/rnote/test/build/target/debug/rnote.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) run
Starting program: /home/chron/builds/rnote/test/build/target/debug/rnote

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n])
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff1bff6c0 (LWP 81146)]
[New Thread 0x7ffff13fe6c0 (LWP 81147)]
[New Thread 0x7ffff0bfd6c0 (LWP 81148)]
[New Thread 0x7fffebfff6c0 (LWP 81149)]
[New Thread 0x7fffeb3ff6c0 (LWP 81151)]
[New Thread 0x7fffeabfe6c0 (LWP 81152)]
   0.342009640s ERROR rnote::overlays: Settings schema is not installed. App settings could not be loaded and won't be saved.
[New Thread 0x7fffd7fff6c0 (LWP 81153)]
[New Thread 0x7fffd77fe6c0 (LWP 81154)]
[New Thread 0x7fffd6ffd6c0 (LWP 81155)]
[New Thread 0x7fffd67fc6c0 (LWP 81156)]
[New Thread 0x7fffd5ffb6c0 (LWP 81157)]
[New Thread 0x7fffd57fa6c0 (LWP 81158)]
[New Thread 0x7fffd4ff96c0 (LWP 81159)]
[New Thread 0x7fffbbfff6c0 (LWP 81160)]
[New Thread 0x7fffbb7fe6c0 (LWP 81161)]
[New Thread 0x7fffb8bff6c0 (LWP 81162)]
[New Thread 0x7fffb9bff6c0 (LWP 81163)]
[New Thread 0x7fff9ffff6c0 (LWP 81164)]
[New Thread 0x7fff9f7fe6c0 (LWP 81165)]
[New Thread 0x7fff9effd6c0 (LWP 81166)]
[Thread 0x7fffbbfff6c0 (LWP 81160) exited]
[Thread 0x7fffd57fa6c0 (LWP 81158) exited]
[Thread 0x7fffbb7fe6c0 (LWP 81161) exited]
[Thread 0x7fffd5ffb6c0 (LWP 81157) exited]
[Thread 0x7fffd67fc6c0 (LWP 81156) exited]
[Thread 0x7fffd4ff96c0 (LWP 81159) exited]
[Thread 0x7fffd6ffd6c0 (LWP 81155) exited]
[Thread 0x7fffeb3ff6c0 (LWP 81151) exited]
[New Thread 0x7fffeb3ff6c0 (LWP 81178)]
[New Thread 0x7fffd4ff96c0 (LWP 81179)]
[Thread 0x7fffd77fe6c0 (LWP 81154) exited]
[Thread 0x7fffd4ff96c0 (LWP 81179) exited]
[New Thread 0x7fffd4ff96c0 (LWP 81180)]
[New Thread 0x7fffd77fe6c0 (LWP 81181)]
[New Thread 0x7fffd6ffd6c0 (LWP 81182)]
[New Thread 0x7fffd67fc6c0 (LWP 81183)]
[New Thread 0x7fffd5ac16c0 (LWP 81184)]
**
Gsk:ERROR:../gtk/gsk/gpu/gskvulkanimage.c:271:gsk_vulkan_image_new: assertion failed: (width > 0 && height > 0)
Bail out! Gsk:ERROR:../gtk/gsk/gpu/gskvulkanimage.c:271:gsk_vulkan_image_new: assertion failed: (width > 0 && height > 0)

Thread 1 "rnote" received signal SIGABRT, Aborted.
0x00007ffff67ad624 in ?? () from /usr/lib/libc.so.6

(gdb) bt full
#0  0x00007ffff67ad624 in ??? () at /usr/lib/libc.so.6
#1  0x00007ffff6753ba0 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff673b582 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff7c21117 in ??? () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7c8ad39 in g_assertion_message_expr () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff71ef8f3 in ??? () at /usr/lib/libgtk-4.so.1
#6  0x00007ffff71efb01 in ??? () at /usr/lib/libgtk-4.so.1
#7  0x00007ffff71edc84 in ??? () at /usr/lib/libgtk-4.so.1
#8  0x00007ffff71d7a22 in ??? () at /usr/lib/libgtk-4.so.1
#9  0x00007ffff71e725f in ??? () at /usr/lib/libgtk-4.so.1
#10 0x00007ffff71e6f80 in ??? () at /usr/lib/libgtk-4.so.1
#11 0x00007ffff71d4fc6 in ??? () at /usr/lib/libgtk-4.so.1
#12 0x00007ffff71e6f80 in ??? () at /usr/lib/libgtk-4.so.1
#13 0x00007ffff71e7220 in ??? () at /usr/lib/libgtk-4.so.1
#14 0x00007ffff71e6f80 in ??? () at /usr/lib/libgtk-4.so.1
#15 0x00007ffff71e7220 in ??? () at /usr/lib/libgtk-4.so.1
#16 0x00007ffff71e6f80 in ??? () at /usr/lib/libgtk-4.so.1
#17 0x00007ffff71e7220 in ??? () at /usr/lib/libgtk-4.so.1
#18 0x00007ffff71e6f80 in ??? () at /usr/lib/libgtk-4.so.1
#19 0x00007ffff71d4fc6 in ??? () at /usr/lib/libgtk-4.so.1
#20 0x00007ffff71e6f80 in ??? () at /usr/lib/libgtk-4.so.1
#21 0x00007ffff71da892 in ??? () at /usr/lib/libgtk-4.so.1
#22 0x00007ffff71e6f80 in ??? () at /usr/lib/libgtk-4.so.1
#23 0x00007ffff71e7220 in ??? () at /usr/lib/libgtk-4.so.1
#24 0x00007ffff71e6f80 in ??? () at /usr/lib/libgtk-4.so.1
#25 0x00007ffff71d4fc6 in ??? () at /usr/lib/libgtk-4.so.1
#26 0x00007ffff71e6f80 in ??? () at /usr/lib/libgtk-4.so.1
#27 0x00007ffff71e7220 in ??? () at /usr/lib/libgtk-4.so.1
#28 0x00007ffff71e6f80 in ??? () at /usr/lib/libgtk-4.so.1
#29 0x00007ffff71da892 in ??? () at /usr/lib/libgtk-4.so.1
#30 0x00007ffff71e6f80 in ??? () at /usr/lib/libgtk-4.so.1
#31 0x00007ffff71e8cff in ??? () at /usr/lib/libgtk-4.so.1
#32 0x00007ffff71e9bc7 in ??? () at /usr/lib/libgtk-4.so.1
#33 0x00007ffff7194f21 in gsk_renderer_render () at /usr/lib/libgtk-4.so.1
#34 0x00007ffff6f4f506 in ??? () at /usr/lib/libgtk-4.so.1
#35 0x00007ffff6f522a9 in ??? () at /usr/lib/libgtk-4.so.1
#36 0x00007ffff70d830a in ??? () at /usr/lib/libgtk-4.so.1
#37 0x00007ffff7ecae5c in ??? () at /usr/lib/libgobject-2.0.so.0
#38 0x00007ffff7ecaf72 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#39 0x00007ffff7ecb034 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#40 0x00007ffff7173b2b in ??? () at /usr/lib/libgtk-4.so.1
#41 0x00007ffff7ecae5c in ??? () at /usr/lib/libgobject-2.0.so.0
#42 0x00007ffff7ecaf72 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#43 0x00007ffff7ecb034 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#44 0x00007ffff7155c7f in ??? () at /usr/lib/libgtk-4.so.1
#45 0x00007ffff71560af in ??? () at /usr/lib/libgtk-4.so.1
#46 0x00007ffff7c6258a in ??? () at /usr/lib/libglib-2.0.so.0
#47 0x00007ffff7c61104 in ??? () at /usr/lib/libglib-2.0.so.0
#48 0x00007ffff7cc4d57 in ??? () at /usr/lib/libglib-2.0.so.0
#49 0x00007ffff7c60535 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#50 0x00007ffff7b09756 in g_application_run () at /usr/lib/libgio-2.0.so.0
#51 0x000055555595f4df in gio::application::ApplicationExtManual::run_with_args<rnote::app::RnApp, alloc::string::String>
    (self=<optimized out>, args=...)
    at /home/chron/builds/rnote/test/build/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/gio-0.20.9/src/application.rs:29
        argc = 1
        argv = alloc::vec::Vec<&str, alloc::alloc::Global> {buf: alloc::raw_vec::RawVec<&str, alloc::alloc::Global> {inner: alloc::raw_vec::RawVecInner<alloc::alloc::Global> {ptr: core::ptr::unique::Unique<u8> {pointer: core::ptr::non_null::NonNull<u8> {pointer: 0x555556d33770}, _marker: core::marker::PhantomData<u8>}, cap: alloc::raw_vec::Cap (1), alloc: alloc::alloc::Global}, _marker: core::marker::PhantomData<&str>}, len: 1}
        argv = alloc::vec::Vec<&str, alloc::alloc::Global> {buf: alloc::raw_vec::RawVec<&str, alloc::alloc::Global> {inner: alloc::raw_vec::RawVecInner<alloc::alloc::Global> {ptr: core::ptr::unique::Unique<u8> {pointer: core::ptr::non_null::NonNull<u8> {pointer: <optimized out>}, _marker: core::marker::PhantomData<u8>}, cap: alloc::raw_vec::Cap (<optimized out>), alloc: alloc::alloc::Global}, _marker: core::marker::PhantomData<&str>}, len: <optimized out>}
        argc = <optimized out>
        exit_code = <optimized out>
#52 gio::application::ApplicationExtManual::run<rnote::app::RnApp> (self=<optimized out>)
    at /home/chron/builds/rnote/test/build/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/gio-0.20.9/src/application.rs:22
#53 0x00005555559e3d79 in rnote::main () at crates/rnote-ui/src/main.rs:86
        app = rnote::app::RnApp {inner: glib::object::TypedObjectRef<rnote::app::imp::RnApp, libadwaita::auto::application::Application> {inner: glib::object::ObjectRef {inner: core::ptr::non_null::NonNull<gobject_sys::GObject> {pointer: 0x555556d338f0}}, imp: core::marker::PhantomData<rnote::app::imp::RnApp>, parent: core::marker::PhantomData<libadwaita::auto::application::Application>}, phantom: core::marker::PhantomData<()>}
```

Might have to redo this after I recompile gtk4 4.18.2 with debug symbols.

**Comment by chronically-late** [comment]
Before you do anything with this...
I've always tested this while connected to USB-C dock with external display for power. With the tablet running on battery/normal USB-C power adapter it seems to run perfectly stable, so this might not be as urgent as it seemed.

**Comment by Doublonmousse** [comment]
@chronically-late is there any logged error in the terminal or does your scaling value is 170 % ?
Also 0.12 is out with gtk 4.18 so you can test the new version

**Comment by chronically-late** [comment]
@Doublonmousse Sorry about the delay in my response.
My scaling factor is 140% for eDP-1 and 120% for DP-1 (the external 3440x1440 USB-docking monitor that was causing the crashes, which don't happen anymore with 0.12 and gtk 4.18) and everything works as it's supposed to.
